version: 2

models:
  - name: stg_management_payroll
    description: Staging model for management payroll data.
    columns:
      - name: EmployeeID
        description: Unique identifier for the employee.
        tests:
          - unique
          - not_null
      - name: Name
        description: Name of the employee.
      - name: Gender
        description: Gender of the employee.
      - name: Age
        description: Age of the employee.
      - name: Department
        description: Department of the employee.
      - name: Position
        description: Position of the employee.
      - name: Salary
        description: Salary of the employee.
      - name: OvertimePay
        description: Overtime pay of the employee.
      - name: PaymentDate
        description: Date of payment.

  - name: stg_performance_management
    description: Staging model for performance management data.
    columns:
      - name: EmployeeID
        description: Unique identifier for the employee.
        tests:
          - not_null
      - name: Name
        description: Name of the employee.
      - name: ReviewPeriod
        description: Period of the review.
      - name: Rating
        description: Performance rating.
      - name: Comments
        description: Comments on the performance.

  - name: stg_recruitment_selection
    description: Staging model for recruitment and selection data.
    columns:
      - name: CandidateID
        description: Unique identifier for the candidate.
        tests:
          - unique
          - not_null
      - name: Name
        description: Name of the candidate.
      - name: Gender
        description: Gender of the candidate.
      - name: Age
        description: Age of the candidate.
      - name: Position
        description: Position applied for.
      - name: ApplicationDate
        description: Date of application.
      - name: Status
        description: Application status.
      - name: InterviewDate
        description: Date of interview.
      - name: OfferStatus
        description: Status of the offer.

  - name: stg_training_development
    description: Staging model for training and development data.
    columns:
      - name: EmployeeID
      - name: Name
      - name: TrainingProgram
      - name: StartDate
      - name: EndDate
      - name: Status